import type { MemberDetail, RelationEdge } from "./types";

export const nodesData: MemberDetail[] = [
	// Parties / Groups
	{
		id: "party_ldp",
		type: "party",
		nameJa: "自由民主党",
		nameEn: "Liberal Democratic Party",
		role: "与党・第一党",
		partyId: "party_ldp",
		description: "高市総裁の下、保守色を強めつつ維新との連立政権を運営。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},
	{
		id: "party_ishin",
		type: "party",
		nameJa: "日本維新の会",
		nameEn: "Japan Innovation Party",
		role: "連立与党",
		partyId: "party_ishin",
		description:
			"高市政権の連立パートナー。12項目の政策合意に基づき改革を推進。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},
	{
		id: "party_komeito",
		type: "party",
		nameJa: "公明党",
		nameEn: "Komeito",
		role: "野党（是々非々）",
		partyId: "party_komeito",
		description: "自公連立を解消し、是々非々の野党へ転換。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},
	{
		id: "party_dpp",
		type: "party",
		nameJa: "国民民主党",
		nameEn: "Democratic Party for the People",
		role: "野党（部分連合）",
		partyId: "party_dpp",
		description:
			"連立には参加せず、政策ごとの協力を模索する「部分連合」的立場。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},
	{
		id: "party_cdp",
		type: "party",
		nameJa: "立憲民主党",
		nameEn: "Constitutional Democratic Party",
		role: "野党第一党",
		partyId: "party_cdp",
		description: "高市政権と対峙する野党第一党。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},
	{
		id: "council_growth",
		type: "party",
		nameJa: "日本成長戦略会議",
		nameEn: "Japan Growth Strategy Council",
		role: "官邸直轄会議",
		partyId: "party_ldp", // Colored as LDP-ish
		description: "積極財政・構造改革の設計図を描く官邸直轄の会議体。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},
	{
		id: "group_private",
		type: "party",
		nameJa: "民間",
		nameEn: "Private Sector Advisors",
		role: "民間専門家グループ",
		partyId: "group_private",
		description:
			"成長戦略本部や官邸会議に助言する民間エコノミスト・実務家のネットワーク。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: [],
	},

	// People - Cabinet & LDP
	{
		id: "takaichi",
		type: "person",
		nameJa: "高市 早苗",
		nameEn: "Sanae Takaichi",
		role: "内閣総理大臣",
		partyId: "party_ldp",
		faction: "無派閥",
		photoUrl: "https://www.mskj.or.jp/wp-content/uploads/2023/03/05-06.png",
		description:
			"日本初の女性首相。「責任ある積極財政」と危機管理・経済安保を掲げる。",
		recentStatements: [
			"[2025/10/21] 物価高最優先: 「高市内閣の最優先事項、これはもう国民の皆様が直面している物価高への対応でございます。」",
			"[2025/11/07] 台湾有事: 「戦艦を使ってですね、そして、武力の行使も伴うものであれば、これはどう考えても存立危機事態になりうるケースであると私は考えます。」",
		],
		recentDietSpeeches: [],
		career: [
			"1993年 初当選",
			"総務大臣",
			"経済安全保障担当大臣",
			"自民党政調会長",
			"2025年 第104代内閣総理大臣",
		],
	},
	{
		id: "kihara",
		type: "person",
		nameJa: "木原 稔",
		nameEn: "Minoru Kihara",
		role: "内閣官房長官",
		partyId: "party_ldp",
		faction: "旧茂木派",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Minoru_Kihara_20190906.jpg",
		description:
			"高市首相の最側近。官邸の司令塔として危機管理・調整を担う。成長戦略会議副議長。",
		recentStatements: [
			"[2025/11/17] 対中批判: 「留学や観光を含む2国間の人的交流を萎縮させるかのような今回の発表、首脳間で確認した戦略的互恵関係の推進、そういった大きな方向性とも相いれない」",
			"[2025/11/17] 政府対応: 「中国側の一連の措置による影響を含め、引き続き状況を注視し適切な対応を行っていく」",
		],
		recentDietSpeeches: [],
		career: ["財務副大臣", "防衛大臣", "2025年 官房長官"],
	},
	{
		id: "katayama",
		type: "person",
		nameJa: "片山 さつき",
		nameEn: "Satsuki Katayama",
		role: "財務大臣",
		partyId: "party_ldp",
		faction: "旧二階派",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Official_portrait_of_Satsuki_Katayama.jpg",
		description:
			"女性初の財務大臣。高市氏の盟友であり、「責任ある積極財政」の実行役。",
		recentStatements: [
			"[2025/10/22] 財政運営: 「『責任ある積極財政』の考え方に基づく経済財政運営を行い...日本経済の力強い成長を実現すること」",
			"[2025/10/22] 燃料価格: 「年内にはしっかり25円下げると、このスピード感と確実感が非常に重要」",
		],
		recentDietSpeeches: [],
		career: ["大蔵省主計官", "地方創生担当相", "2025年 財務大臣"],
	},
	{
		id: "aso",
		type: "person",
		nameJa: "麻生 太郎",
		nameEn: "Taro Aso",
		role: "自民党副総裁",
		partyId: "party_ldp",
		faction: "麻生派",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Taro_Aso.jpg",
		description: "高市政権誕生を主導。党内最大の重鎮として政権運営を支える。",
		recentStatements: [
			"[2025/11/16] 財政規律: 「単にいくら予算をつけるといったことだけでなく...規制改革などもしっかり議論してほしい」",
			"[2025/10/04] 総裁選指示: 「党員・党友票が多い候補に（投票せよ）」",
		],
		recentDietSpeeches: [],
		career: ["第92代内閣総理大臣", "副総理・財務大臣", "自民党副総裁"],
	},
	{
		id: "sato",
		type: "person",
		nameJa: "佐藤 啓",
		nameEn: "Kei Sato",
		role: "官房副長官(参)",
		partyId: "party_ldp",
		faction: "無派閥",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Kei_Sato_20210812.jpg",
		description:
			"高市氏と同郷（奈良）の腹心。「深く信頼」され、逆風下でも続投。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["総務大臣政務官", "参議院議員(奈良)"],
	},
	{
		id: "ozaki",
		type: "person",
		nameJa: "尾崎 正直",
		nameEn: "Masanao Ozaki",
		role: "官房副長官(衆)",
		partyId: "party_ldp",
		faction: "旧二階派",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Masanao_Ozaki_2022.png",
		description:
			"元高知県知事。実務能力を買われ官邸中枢へ。佐藤副長官の代役もこなす。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["高知県知事", "デジタル政務官", "2025年 官房副長官"],
	},
	{
		id: "onoda",
		type: "person",
		nameJa: "小野田 紀美",
		nameEn: "Kimi Onoda",
		role: "経済安全保障相",
		partyId: "party_ldp",
		faction: "無派閥",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Kimi_Onoda.jpg",
		description:
			"高市氏の熱烈な支持者であり「チーム高市」の中核。経済安保を担当。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["参議院議員", "防衛大臣政務官", "2025年 経済安保相"],
	},
	{
		id: "matsumoto",
		type: "person",
		nameJa: "松本 尚",
		nameEn: "Hisashi Matsumoto",
		role: "デジタル大臣",
		partyId: "party_ldp",
		faction: "無派閥",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Hisashi_Matsumoto_2023.jpg",
		description:
			"医師出身。石破前政権に近いが、専門性を買われ入閣。サイバー安全保障も担当。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["医師", "防衛大臣政務官", "2025年 デジタル大臣"],
	},
	{
		id: "kiuchi",
		type: "person",
		nameJa: "城内 実",
		nameEn: "Minoru Kiuchi",
		role: "成長戦略担当相",
		partyId: "party_ldp",
		faction: "無派閥",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Minoru_Kiuchi_portrait_2020.jpg",
		description:
			"高市氏の同志。安倍元首相と共に高市氏を支えた保守派。成長戦略会議副議長。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["外務副大臣", "経済安保相", "2025年 成長戦略相"],
	},
	{
		id: "motegi",
		type: "person",
		nameJa: "茂木 敏充",
		nameEn: "Toshimitsu Motegi",
		role: "外務大臣",
		partyId: "party_ldp",
		faction: "茂木派",
		photoUrl: "https://www.jiji.com/img/giin/syu/2916.jpg",
		description:
			"茂木派領袖。総裁選での協力の見返りとして重要閣僚に。政権のバランサー。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["自民党幹事長", "外務大臣", "経産大臣"],
	},
	{
		id: "akazawa",
		type: "person",
		nameJa: "赤澤 亮正",
		nameEn: "Ryosei Akazawa",
		role: "経済産業大臣",
		partyId: "party_ldp",
		faction: "無派閥",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Ryosei_Akazawa_2023.jpg",
		description:
			"石破茂氏の側近だが、挙党態勢の一環として入閣。実務家として評価。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["内閣府副大臣", "経済再生担当相", "2025年 経産相"],
	},
	{
		id: "ueno",
		type: "person",
		nameJa: "上野 賢一郎",
		nameEn: "Kenichiro Ueno",
		role: "厚生労働大臣",
		partyId: "party_ldp",
		faction: "旧森山派",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Kenichiro_Ueno.jpg",
		description: "旧森山派からの入閣。実務に精通した手堅い仕事師。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["財務副大臣", "国交政務官", "2025年 厚労相"],
	},
	{
		id: "suzuki",
		type: "person",
		nameJa: "鈴木 俊一",
		nameEn: "Shunichi Suzuki",
		role: "自民党幹事長",
		partyId: "party_ldp",
		faction: "麻生派",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Shunichi_Suzuki_20211004.jpg",
		description: "麻生派の重鎮。党運営の要として官邸と国会を結ぶ。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["財務大臣", "総務会長", "2025年 幹事長"],
	},

	// People - Ishin
	{
		id: "yoshimura",
		type: "person",
		nameJa: "吉村 洋文",
		nameEn: "Hirofumi Yoshimura",
		role: "維新代表",
		partyId: "party_ishin",
		faction: "",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Hirofumi_Yoshimura.jpg",
		description:
			"日本維新の会代表。高市首相との連立を決断したパートナー。「相思相愛」とも。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["大阪府知事", "大阪市長", "衆議院議員"],
	},
	{
		id: "fujita",
		type: "person",
		nameJa: "藤田 文武",
		nameEn: "Fumitake Fujita",
		role: "維新幹事長",
		partyId: "party_ishin",
		faction: "",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Fumitake_Fujita_2022-6-26.jpg",
		description:
			"維新の若き司令塔。連立協議の実務窓口であり、官邸と頻繁に連携。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["維新国対委員長", "衆議院議員"],
	},
	{
		id: "endo",
		type: "person",
		nameJa: "遠藤 敬",
		nameEn: "Takashi Endo",
		role: "首相補佐官",
		partyId: "party_ishin",
		faction: "",
		photoUrl: "https://o-ishin.jp/member/images/member/endo_takashi.jpg",
		description:
			"維新所属ながら首相補佐官に起用された連立のキーマン。「陰の実力者」。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["維新国対委員長", "2025年 首相補佐官"],
	},

	// People - Other Parties
	{
		id: "tamaki",
		type: "person",
		nameJa: "玉木 雄一郎",
		nameEn: "Yuichiro Tamaki",
		role: "国民民主代表",
		partyId: "party_dpp",
		faction: "",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Yuichiro_Tamaki_IMG_5649-1_20160903.jpg",
		description: "政策ごとの協力を模索する「部分連合」パートナー。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["財務官僚", "国民民主党代表"],
	},
	{
		id: "noda",
		type: "person",
		nameJa: "野田 佳彦",
		nameEn: "Yoshihiko Noda",
		role: "立憲民主代表",
		partyId: "party_cdp",
		faction: "",
		photoUrl:
			"https://commons.wikimedia.org/wiki/Special:FilePath/Official_portrait_of_Prime_Minister_Yoshihiko_Noda.jpg",
		description:
			"野党第一党党首。高市氏とは国会論戦で対峙するが、松下政経塾の先輩としてリスペクトも。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["第95代内閣総理大臣", "財務大臣"],
	},
	{
		id: "saito",
		type: "person",
		nameJa: "斉藤 鉄夫",
		nameEn: "Tetsuo Saito",
		role: "公明党代表",
		partyId: "party_komeito",
		faction: "",
		photoUrl: "https://www.jiji.com/img/giin/syu/1251.jpg",
		description: "公明党代表。自公連立解消後、是々非々の立場で党を率いる。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["環境大臣", "国土交通大臣", "公明党代表"],
	},

	// People - Private Sector
	{
		id: "wakatabe",
		type: "person",
		nameJa: "若田部 昌澄",
		nameEn: "Masazumi Wakatabe",
		role: "元日銀副総裁",
		partyId: "group_private",
		faction: "",
		photoUrl:
			"https://www.waseda.jp/fpse/pse/assets/uploads/2018/03/dee5f4967a99da82703ed67ae78d65ac-940x705.png",
		description:
			"積極財政・リフレ政策を提唱する学者で、成長戦略本部のブレーンとして助言。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["早稲田大学教授", "第31代日銀副総裁"],
	},
	{
		id: "aida",
		type: "person",
		nameJa: "会田 卓司",
		nameEn: "Takuji Aida",
		role: "クレディ・アグリコル証券",
		partyId: "group_private",
		faction: "",
		photoUrl:
			"https://dol.ismcdn.jp/mwimgs/6/f/-/img_6fe6dee948a224b99b933007fa98d2cc98506.jpg",
		description:
			"市場分析に基づき政府の政策運営をサポートするシニアエコノミスト。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["クレディ・アグリコル証券チーフエコノミスト"],
	},
	{
		id: "kataoka",
		type: "person",
		nameJa: "片岡 剛士",
		nameEn: "Takeshi Kataoka",
		role: "PwC役員",
		partyId: "group_private",
		faction: "",
		photoUrl:
			"https://dol.ismcdn.jp/mwimgs/1/7/-/img_174e63b9de38b92ba65261debe00897e145738.jpg",
		description:
			"民間企業の視点から成長戦略や財政政策を提言するPwCのエコノミスト。",
		recentStatements: [],
		recentDietSpeeches: [],
		career: ["元日銀審議委員", "PwCコンサルティング執行役員"],
	},
];

export const edgesData: RelationEdge[] = [
	// Cabinet
	{
		id: "cab_takaichi_kihara",
		source: "takaichi",
		target: "kihara",
		labelJa: "官房長官",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_katayama",
		source: "takaichi",
		target: "katayama",
		labelJa: "財務大臣",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_onoda",
		source: "takaichi",
		target: "onoda",
		labelJa: "経済安保相",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_matsumoto",
		source: "takaichi",
		target: "matsumoto",
		labelJa: "デジタル相",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_kiuchi",
		source: "takaichi",
		target: "kiuchi",
		labelJa: "成長戦略相",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_motegi",
		source: "takaichi",
		target: "motegi",
		labelJa: "外務大臣",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_akazawa",
		source: "takaichi",
		target: "akazawa",
		labelJa: "経産大臣",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_ueno",
		source: "takaichi",
		target: "ueno",
		labelJa: "厚労大臣",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_sato",
		source: "takaichi",
		target: "sato",
		labelJa: "官房副長官",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_ozaki",
		source: "takaichi",
		target: "ozaki",
		labelJa: "官房副長官",
		relationType: "cabinet",
	},
	{
		id: "cab_takaichi_endo",
		source: "takaichi",
		target: "endo",
		labelJa: "首相補佐官",
		relationType: "cabinet",
	},

	// Party Leadership & Support
	{
		id: "party_aso_takaichi",
		source: "aso",
		target: "takaichi",
		labelJa: "政治的後見",
		relationType: "mentor",
	},
	{
		id: "party_takaichi_suzuki",
		source: "takaichi",
		target: "suzuki",
		labelJa: "幹事長",
		relationType: "party_leadership",
	},
	{
		id: "party_aso_suzuki",
		source: "aso",
		target: "suzuki",
		labelJa: "義兄弟・派閥",
		relationType: "ally",
	},
	{
		id: "party_aso_motegi",
		source: "aso",
		target: "motegi",
		labelJa: "連携",
		relationType: "ally",
	},

	// Personal Relations (Allies)
	{
		id: "ally_takaichi_kihara",
		source: "takaichi",
		target: "kihara",
		labelJa: "最側近",
		relationType: "ally",
	},
	{
		id: "ally_takaichi_katayama",
		source: "takaichi",
		target: "katayama",
		labelJa: "盟友・推薦人",
		relationType: "ally",
	},
	{
		id: "ally_takaichi_onoda",
		source: "takaichi",
		target: "onoda",
		labelJa: "チーム高市",
		relationType: "ally",
	},
	{
		id: "ally_takaichi_kiuchi",
		source: "takaichi",
		target: "kiuchi",
		labelJa: "同志",
		relationType: "ally",
	},
	{
		id: "ally_takaichi_sato",
		source: "takaichi",
		target: "sato",
		labelJa: "深く信頼(奈良)",
		relationType: "regional",
	},

	// Coalition (Ishin)
	{
		id: "coal_ldp_ishin",
		source: "party_ldp",
		target: "party_ishin",
		labelJa: "連立政権",
		relationType: "coalition",
	},
	{
		id: "coal_takaichi_yoshimura",
		source: "takaichi",
		target: "yoshimura",
		labelJa: "連立/12項目の政策合意",
		relationType: "coalition",
	},
	{
		id: "coal_kihara_fujita",
		source: "kihara",
		target: "fujita",
		labelJa: "実務調整",
		relationType: "coalition",
	},
	{
		id: "coal_kihara_takaichi",
		source: "kihara",
		target: "takaichi",
		labelJa: "ガソリン暫定税率廃止/議員定数削減/社会保障改革などを要求",
		relationType: "coalition",
	},
	{
		id: "coal_endo_ishin",
		source: "endo",
		target: "party_ishin",
		labelJa: "パイプ役",
		relationType: "coalition",
	},

	// Other Parties
	{
		id: "rel_ldp_komeito",
		source: "takaichi",
		target: "saito",
		labelJa: "連立解消",
		relationType: "former_coalition",
	},
	{
		id: "rel_takaichi_tamaki",
		source: "takaichi",
		target: "tamaki",
		labelJa: "部分連合",
		relationType: "partial_cooperation",
	},
	{
		id: "rel_takaichi_noda",
		source: "takaichi",
		target: "noda",
		labelJa: "政策論争・先輩後輩",
		relationType: "opposition",
	},
	{
		id: "alumni_takaichi_noda",
		source: "takaichi",
		target: "noda",
		labelJa: "松下政経塾",
		relationType: "alumni",
	},

	// Private Sector Advisors
	{
		id: "adv_wakatabe",
		source: "wakatabe",
		target: "takaichi",
		labelJa: "成長戦略本部にて関与",
		relationType: "advisor",
	},
	{
		id: "adv_aida",
		source: "aida",
		target: "takaichi",
		labelJa: "成長戦略本部にて関与",
		relationType: "advisor",
	},
	{
		id: "adv_kataoka",
		source: "kataoka",
		target: "takaichi",
		labelJa: "成長戦略本部にて関与",
		relationType: "advisor",
	},

	// Council
	{
		id: "council_takaichi",
		source: "takaichi",
		target: "council_growth",
		labelJa: "議長",
		relationType: "council_member",
	},
	{
		id: "council_kihara",
		source: "kihara",
		target: "council_growth",
		labelJa: "副議長",
		relationType: "council_member",
	},
	{
		id: "council_kiuchi",
		source: "kiuchi",
		target: "council_growth",
		labelJa: "副議長",
		relationType: "council_member",
	},
];
